# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='image name')),
                ('url', models.CharField(max_length=255, verbose_name='image url')),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='Gender')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
